--DODATKOWE ŹRÓDŁA MUZYCZNE DO VA_SOURCES

DELETE FROM va_sources;

INSERT INTO va_sources (youtube_link, title, artist, is_video) VALUES
 ('MMryYio0v6k', 'Futurama 3', 'Quebonafide', TRUE),
 ('WFCr2UrLOV8', 'Kamień z Serca', 'Bedoes 2115', TRUE),
 ('7gAnnvDIH8Y', 'Opowieści z Doliny Smoków', 'Bedoes & Lanek', TRUE),
 ('JKahEPv9xFM', 'Nóż motylkowy', 'Chivas feat. White2115', TRUE),
 ('s7Z75i_xYZg', 'Hot16Challenge2', 'Szpaku', TRUE),
 ('jn6ZnlgfnO4', 'Dopóki się nie znüdzisz', 'MIÜ feat. Zalia', TRUE),
 ('EY6rrJ3TFHA', 'PG$', 'Young Leosia, bambi', TRUE),
 ('1f4snkig1nM', 'Billy Kid', 'ReTo', TRUE),
 ('RspDppBZumA', 'JEREMY SOCHAN', 'OKI', TRUE),
 ('AjrtRgZdzgU', 'Schodki', 'MATA', TRUE),
 ('Fj33kYKczGk', 'Miłość w Zakopanem', 'Sławomir', FALSE),
 ('jAa4BOwHdRI', 'Ale Ale Aleksandra', 'Andre', TRUE),
 ('XTIWumWC4bQ', 'Nadzieja', 'Skaner', FALSE),
 ('CjKDFW53jbE', 'Cztery osiemnastki', 'Tomasz Niecik', TRUE),
 ('KfUDsnSpesc', 'ŁYDKA GRUBASA - Rapapara', 'Łydka Grubasa', TRUE),
 ('FmjFgt_ggAw', 'LATO LATO W KOŁOBRZEGU', 'nieznany', TRUE),
 ('nGWqUR-wW7E', 'Tak, tak żono moja', 'B-QLL', TRUE),
 ('KC2yqAUU1ks', 'Erotyczne Pif-Paf', 'Figo i Samogony', FALSE),
 ('f0MphnfQCzw', 'Dziś Ci To Powiem', 'Exaited', TRUE),
 ('9XolBQsGGBM', 'Tańcz Tańcz Tańcz', 'Long & Junior', TRUE),
 ('LDjwv_poguo', 'Za każdą chwilę z Tobą', 'WEEKEND', TRUE),
 ('Wp57PXBB7Xg', 'Zawsze z Tobą chciałbym być', 'Ich Troje', TRUE),
 ('JvxG3zl_WhU', 'Ona tańczy dla mnie', 'WEEKEND', TRUE),
 ('c2i4h7Q-8sA', 'Jesteś szalona', 'BOYS', TRUE),
 ('LCcIx6bCcr8', 'Ona By Tak Chciała', 'Ronnie Ferrari', FALSE),
 ('2KDlDuS6r6I', 'Shotta Flow Remix', 'NLE Choppa ft. Blueface', TRUE),
 ('H3c0F3oGZ4I', '6locc 6a6y', 'Lil Loaded', TRUE),
 ('0II-EFw9J0A', 'Camelot', 'NLE Choppa', TRUE),
 ('cwQgjq0mCdE', 'I Love It', 'Kanye West & Lil Pump feat. Adele Givens', TRUE),
 ('E8gmARGvPlI', 'Last Christmas', 'Wham!', TRUE),
 ('h_QNYTrHZ2c', 'King Bruce Lee Karate Mistrz', 'Franek Kimono', FALSE),
 ('VYOjWnS4cMY', 'This Is America', 'Childish Gambino', TRUE),
 ('w2Ov5jzm3j8', 'Old Town Road (Official Movie) ft. Billy Ray Cyrus', 'Lil Nas X & Billy Ray Cyrus', TRUE),
 ('m4_9TFeMfJE', 'Paint The Town Red', 'Doja Cat', TRUE);


-- ('X5P2uJELu5A', 'Don Pedalini', 'Franek Masturbatra', FALSE),
-- ('qQzdAsjWGPg', 'My Way', 'Frank Sinatra', FALSE),
-- ('CFlMy48ui9s', 'Fly me to the moon', 'Frank Sinatra', FALSE),
-- ('ckbMWsBfO8o', 'SYRENKA', 'TUSZOL & WRONEK', TRUE),
-- ('KQ6zr6kCPj8', 'Party Rock Anthem', 'LMFAO', TRUE),
-- ('9bZkp7q19f0', 'Gangnam Style (Official Video)', 'PSY', TRUE),
-- ('DyDfgMOUjCI', 'Bad Guy (Official Video)', 'Billie Eilish', TRUE),
-- ('YF1R0hc5Q2I', 'Take Five', 'The Dave Brubeck Quartet', FALSE),
-- ('p7DgMbhPRFg', 'What a Wonderful World', 'Louis Armstrong', FALSE),
-- ('vUSzL2leaFM', 'Unforgettable', 'Nat King Cole', FALSE),
-- ('2nGKqH26xlg', 'Dream a Little Dream of Me', 'Ella Fitzgerald & Louis Armstrong', FALSE),
-- ('kTFZyl7hfBw', 'Beyond the Sea', 'Bobby Darin', FALSE),
-- ('zv1a_9wTv60', 'Blue Moon', 'The Marcels', FALSE),
-- ('mN7LW0Y00kE', 'My Girl', 'The Temptations', FALSE),
-- ('92cwKCU8Z5c', 'Stand by Me', 'Ben E. King', FALSE),
-- ('tAGnKpE4NCI', 'Nothing Else Matters', 'Metallica', FALSE),
-- ('0yW7w8F2TVA', 'House of the Rising Sun', 'The Animals', FALSE),
-- ('J---aiyznGQ', 'Canon in D', 'Pachelbel', FALSE),
-- ('K3Qzzggn--s', 'Jailhouse Rock', 'Elvis Presley', FALSE),
-- ('WGiX5tbLKiY', 'Can’t Help Falling in Love', 'Elvis Presley', FALSE),
-- ('QkF3oxziUI4', 'Stairway to Heaven', 'Led Zeppelin', FALSE),
-- ('u9Dg-g7t2l4', 'Hurt', 'Johnny Cash', FALSE),
-- ('6Ejga4kJUts', 'Zombie', 'The Cranberries', FALSE),
-- ('7QU1nvuxaMA', 'Careless Whisper', 'George Michael', FALSE),
-- ('kMlQpVuwxXk', 'Sultans of Swing', 'Dire Straits', FALSE),
-- ('8ZcmTl_1ER8', 'Africa', 'Toto', FALSE),
-- ('ruAi4VBoBSM', 'Every Breath You Take', 'The Police', FALSE),
-- ('OMOGaugKpzs', 'Sweet Dreams (Are Made of This)', 'Eurythmics', FALSE),
-- ('LatorN4P9aA', 'Take On Me', 'a-ha', FALSE),
-- ('3JWTaaS7LdU', 'I Will Always Love You', 'Whitney Houston', FALSE),
-- ('B7xai5u_tnk', 'Eye of the Tiger', 'Survivor', FALSE),
-- ('CD-E-LDc384', 'Hotel California', 'Eagles', FALSE),
-- ('nCgQDjiotG0', 'Halo', 'Beyoncé', FALSE),
-- ('IP0KB2XC7fE', 'I Want It That Way', 'Backstreet Boys', FALSE),
-- ('3y5pSXA2CAE', 'Toxic', 'Britney Spears', FALSE),
-- ('mWRsgZuwf_8', 'Demons', 'Imagine Dragons', FALSE),
-- ('mCdA4bJAGGk', 'Heat Waves', 'Glass Animals', FALSE),
-- ('HhpFsFzOm9I', 'Riders on the Storm', 'The Doors', FALSE),
-- ('SByymar3bds', 'Space Oddity', 'David Bowie', FALSE),
-- ('rY0WxgSXdEE', 'Don’t Stop Believin’', 'Journey', FALSE),
-- ('YVkUvmDQ3HY', 'Smack That', 'Akon ft. Eminem', FALSE),
-- ('eY52Zsg-KVI', 'Clint Eastwood', 'Gorillaz', FALSE),
-- ('vxoVLYy8rlI', 'Wonderful Tonight', 'Eric Clapton', FALSE),
-- ('fTkHFQC3wow', 'You Are So Beautiful', 'Joe Cocker', FALSE),
-- ('6SFNW5F8K9Y', 'Ain’t No Sunshine', 'Bill Withers', FALSE),
-- ('c7-3v1bG0Ww', 'Let It Be', 'The Beatles', FALSE),
-- ('kXYiU_JCYtU', 'Numb', 'Linkin Park', FALSE),
-- ('rYEDA3JcQqw', 'Rolling in the Deep', 'Adele', FALSE),
-- ('QDYfEBY9NM4', 'All of Me', 'John Legend', FALSE),
-- ('tt2k8PGm-TI', 'Diamonds', 'Rihanna', FALSE),
-- ('pXRviuL6vMY', 'Stressed Out', 'Twenty One Pilots', FALSE),
-- ('RgKAFK5djSk', 'See You Again', 'Wiz Khalifa ft. Charlie Puth', FALSE),
-- ('OPA3620BrF0', 'Imagine', 'John Lennon', FALSE),
-- ('5IsSpAOD6K8', 'Light My Fire', 'The Doors', FALSE),
-- ('YgSPaXgAdzE', 'Ring of Fire', 'Johnny Cash', FALSE),
-- ('2vjPBrBU-TM', 'Chandelier', 'Sia', FALSE),
-- ('yKNxeF4KMsY', 'Everybody Wants to Rule the World', 'Tears for Fears', FALSE),
-- ('dQw4w9WgXcQ', 'Never Gonna Give You Up', 'Rick Astley', TRUE),
-- ('3JZ4pnNtyxQ', 'Take On Me', 'a-ha', TRUE),
-- ('fJ9rUzIMcZQ', 'Bohemian Rhapsody', 'Queen', TRUE),
-- ('ktvTqknDobU', 'Radioactive', 'Imagine Dragons', TRUE),
-- ('hTWKbfoikeg', 'Smells Like Teen Spirit', 'Nirvana', TRUE),
-- ('L_jWHffIx5E', 'Wonderwall', 'Oasis', TRUE),
-- ('eVTXPUF4Oz4', 'In The End', 'Linkin Park', TRUE),
-- ('YQHsXMglC9A', 'Hello', 'Adele', TRUE),
-- ('pRpeEdMmmQ0', 'Waka Waka', 'Shakira', TRUE),
-- ('7wtfhZwyrcc', 'Believer', 'Imagine Dragons', TRUE),
-- ('UceaB4D0jpo', 'Animals', 'Maroon 5', TRUE),
-- ('OPf0YbXqDm0', 'Uptown Funk', 'Mark Ronson ft. Bruno Mars', TRUE),
-- ('CevxZvSJLk8', 'Roar', 'Katy Perry', TRUE),
-- ('0KSOMA3QBU0', 'Dark Horse', 'Katy Perry', TRUE),
-- ('2Vv-BfVoq4g', 'Perfect', 'Ed Sheeran', TRUE),
-- ('K5KAc5CoCuk', 'Shape of You', 'Ed Sheeran', TRUE),
-- ('hLQl3WQQoQ0', 'Someone Like You', 'Adele', TRUE),
-- ('uelHwf8o7_U', 'Love The Way You Lie', 'Eminem ft. Rihanna', TRUE),
-- ('09R8_2nJtjg', 'Sugar', 'Maroon 5', TRUE),
-- ('rubvXz6iAGw', 'Freedom', 'Akon', FALSE),
-- ('4NRXx6U8ABQ', 'Blinding Lights', 'The Weeknd', TRUE),
-- ('60ItHLz5WEA', 'Faded', 'Alan Walker', TRUE),
-- ('y6120QOlsfU', 'Sandstorm', 'Darude', FALSE),
-- ('LsoLEjrDogU', 'Levels', 'Avicii', TRUE),
-- ('IcrbM1l_BoI', 'Wake Me Up', 'Avicii', TRUE),
-- ('YykjpeuMNEk', 'Hymn for the Weekend', 'Coldplay', TRUE),
-- ('dvgZkm1xWPE', 'Viva La Vida', 'Coldplay', TRUE),
-- ('09g5s2v0kD8', 'Zombie', 'The Cranberries', TRUE),
-- ('vNoKguSdy4Y', 'All About That Bass', 'Meghan Trainor', TRUE),
-- ('bESGLojNYSo', 'Hot n Cold', 'Katy Perry', TRUE),
-- ('iEPTlhBmwRg', 'Titanium', 'David Guetta ft. Sia', TRUE),
-- ('lp-EO5I60KA', 'Thinking Out Loud', 'Ed Sheeran', TRUE),
-- ('C-u5WLJ9Yk4', 'Wrecking Ball', 'Miley Cyrus', TRUE),
-- ('UqyT8IEBkvY', 'Happy', 'Pharrell Williams', TRUE),
-- ('gCYcHz2k5x0', 'Turn Down for What', 'DJ Snake & Lil Jon', TRUE),
-- ('HgzGwKwLmgM', 'Dont Stop Me Now', 'Queen', TRUE),
-- ('Zi_XLOBDo_Y', 'Billie Jean', 'Michael Jackson', TRUE),
-- ('sOnqjkJTMaA', 'Thriller', 'Michael Jackson', TRUE),
-- ('oRdxUFDoQe0', 'Smooth Criminal', 'Michael Jackson', TRUE),
-- ('nfWlot6h_JM', 'Shake It Off', 'Taylor Swift', TRUE),
-- ('WA4iX5D9Z64', 'Blank Space', 'Taylor Swift', TRUE),
-- ('VYOjWnS4cMY', 'This Is America', 'Childish Gambino', TRUE),
-- ('SbUBMklQSVU', 'Stressed Out', 'Twenty One Pilots', TRUE),
-- ('Pw-0pbY9JeU', 'Thunder', 'Imagine Dragons', TRUE),
-- ('f2JuxM-snGc', 'Seven Nation Army', 'The White Stripes', TRUE);
